@apiUrl = https://todolist-rocket-tgv5.onrender.com

POST {{apiUrl}}/users/ HTTP/1.1
Content-Type: application/json

{
  "username": "doug",
  "name": "Douglas",
  "password": "123"
}

###

POST {{apiUrl}}/tasks/ HTTP/1.1
Authorization: Basic doug:123
Content-Type: application/json

{
  "title":"Task",
  "description": "Tarefa de teste Solange",
  "priority": "ALTA",
  "startAt": "2023-10-15T17:30:00",
  "endAt": "2023-11-15T17:35:00"
}

###

GET {{apiUrl}}/tasks/ HTTP/1.1
Authorization: Basic doug:123
Content-Type: application/json


###

PUT {{apiUrl}}/tasks/8cace10a-d903-496d-bed2-113eab5131cf HTTP/1.1
Authorization: Basic doug:123
Content-Type: application/json

{
  "title": "Update task",
  "priority": "MEDIA"
}